# Generated by Django 5.2.14 on 2026-06-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("category", models.CharField(max_length=100)),
                ("summary", models.TextField()),
                ("tools", models.JSONField(default=list)),
                ("problem", models.TextField()),
                ("approach", models.TextField()),
                ("result", models.TextField()),
                ("business_impact", models.TextField()),
                ("status", models.CharField(default="In Progress", max_length=50)),
                ("demo_url", models.URLField(blank=True, null=True)),
                ("repo_url", models.URLField(blank=True, null=True)),
                ("features", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
