# Generated by Django 5.2.14 on 2026-06-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="dash_app_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
